export const AUTH_USER = "AUTH_USER";
export const GET_ALL_FARMERS = "GET_ALL_FARMERS";
export const GET_SPECIFIC_FARMER = "GET_SPECIFIC_FARMER";
export const CLEAR_FARMER = "CLEAR_FARMER";

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";

export const GET_ERRORS = "GET_ERRORS";

export const LOGIN_FAIL = "LOGIN_FAIL";

export const ADMIN_LOGIN_SUCCESS = "ADMIN_LOGIN_SUCCESS";
